# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pod_local_test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pod_local_test

  #要修改只能到原始工程去修改
  #pod 'my_lib', :podspec=>'/Users/hbro.hf/Desktop/my_files/mac_dev/demo/pod_loacl/my_lib/my_lib.podspec'

  #这种方式可以直接开搞
  pod 'my_lib', :path=>'/Users/hbro.hf/Desktop/my_files/mac_dev/demo/pod_loacl/my_lib'


end
